[package]
name = "frunk"
version = "0.1.19"
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "Frunk provides developers with a number of functional programming tools like HList, Generic, LabelledGeneric, Validated, Monoid, Semigroup and friends."
license = "MIT"
homepage = "https://github.com/lloydmeta/frunk"
keywords = [ "HList", "Generic", "Validated", "Semigroup", "Monoid"]

[dev-dependencies]
time = "0.1.36"

[dependencies.frunk_core]
path = "core"
version = "0.0.9"

[dependencies.frunk_derives]
path = "derives"
version = "0.0.10"